/**
 * Centralized mock data for all API routes.
 *
 * WHY: Previously each API route (accounts, holdings, net-worth, transactions)
 * had its own copy of mock data, leading to drift and inconsistency.
 * All routes now import from here as a single source of truth.
 *
 * These are used as fallbacks when the database is not connected.
 * To replace with real data: connect PostgreSQL and run `npm run db:seed`.
 */

import type {
  AccountWithStats,
  HoldingWithAccount,
  NetWorthSummary,
  TransactionWithRelations,
} from '@/types'

// ---------------------------------------------------------------------------
// Accounts
// ---------------------------------------------------------------------------

export const MOCK_ACCOUNTS: AccountWithStats[] = [
  {
    id: 'a3',
    name: 'Discount Bank Checking',
    type: 'BANK',
    currency: 'ILS',
    balance: 87500,
    lastSyncedAt: null,
    isActive: true,
    metadata: {
      bankCode: '11',
      branchNumber: '123',
      accountNumber: '****4567',
      country: 'IL',
      adapterStatus: 'manual',
    },
    createdAt: new Date(Date.now() - 180 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    holdingCount: 1,
    totalValue: 87500,
  },
  {
    id: 'a2',
    name: 'Trezor – Crypto Wallet',
    type: 'CRYPTO',
    currency: 'USD',
    balance: 87382,
    lastSyncedAt: null,
    isActive: true,
    metadata: {
      // BTC_ADDRESS / ETH_ADDRESS in .env activates watch-only mode.
      // Without an address, manual mode is used: quantity × live price.
      btcAddress: process.env.BTC_ADDRESS ?? '(manual mode — no address needed)',
      ethAddress: process.env.ETH_ADDRESS ?? '(not configured)',
      watchOnly: !!process.env.BTC_ADDRESS,
      adapterStatus: process.env.BTC_ADDRESS ? 'live' : 'manual',
    },
    createdAt: new Date(Date.now() - 160 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    holdingCount: 2,
    totalValue: 87382,
  },
  {
    id: 'a1',
    name: 'Excellence Trade',
    type: 'BROKERAGE',
    currency: 'USD',
    balance: 198840,
    lastSyncedAt: null,
    isActive: true,
    metadata: {
      broker: 'Excellence Trade',
      accountType: 'Individual',
      country: 'IL',
      csvSupported: true,
      adapterStatus: 'manual',
    },
    createdAt: new Date(Date.now() - 185 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    holdingCount: 5,
    totalValue: 198840,
  },
]

// ---------------------------------------------------------------------------
// Holdings
// ---------------------------------------------------------------------------

const mockBrokerageAccount = {
  id: 'a1',
  name: 'Excellence Trade',
  type: 'BROKERAGE' as const,
  currency: 'USD',
  balance: 198840,
  lastSyncedAt: null,
  isActive: true,
  metadata: {},
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

const mockCryptoAccount = {
  id: 'a2',
  name: 'Trezor – Crypto Wallet',
  type: 'CRYPTO' as const,
  currency: 'USD',
  balance: 87382,
  lastSyncedAt: null,
  isActive: true,
  metadata: {},
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

const mockBankAccount = {
  id: 'a3',
  name: 'Discount Bank Checking',
  type: 'BANK' as const,
  currency: 'ILS',
  balance: 87500,
  lastSyncedAt: null,
  isActive: true,
  metadata: {},
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
}

export const MOCK_HOLDINGS: HoldingWithAccount[] = [
  {
    id: 'h1',
    accountId: 'a1',
    symbol: 'AAPL',
    name: 'Apple Inc.',
    assetClass: 'STOCK',
    quantity: 50,
    avgCostBasis: 155.0,
    currentPrice: 189.30,
    currentValue: 9465,
    dailyChangePercent: 1.24,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBrokerageAccount,
  },
  {
    id: 'h2',
    accountId: 'a1',
    symbol: 'GOOGL',
    name: 'Alphabet Inc.',
    assetClass: 'STOCK',
    quantity: 30,
    avgCostBasis: 140.0,
    currentPrice: 178.15,
    currentValue: 5344.50,
    dailyChangePercent: -0.87,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBrokerageAccount,
  },
  {
    id: 'h3',
    accountId: 'a1',
    symbol: 'VOO',
    name: 'Vanguard S&P 500 ETF',
    assetClass: 'ETF',
    quantity: 40,
    avgCostBasis: 420.0,
    currentPrice: 492.50,
    currentValue: 19700,
    dailyChangePercent: 0.53,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBrokerageAccount,
  },
  {
    id: 'h4',
    accountId: 'a1',
    symbol: 'QQQ',
    name: 'Invesco QQQ Trust',
    assetClass: 'ETF',
    quantity: 25,
    avgCostBasis: 380.0,
    currentPrice: 469.80,
    currentValue: 11745,
    dailyChangePercent: 0.92,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBrokerageAccount,
  },
  {
    id: 'h5',
    accountId: 'a1',
    symbol: 'VTI',
    name: 'Vanguard Total Stock Market ETF',
    assetClass: 'ETF',
    quantity: 60,
    avgCostBasis: 215.0,
    currentPrice: 248.90,
    currentValue: 14934,
    dailyChangePercent: 0.47,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBrokerageAccount,
  },
  {
    id: 'h6',
    accountId: 'a2',
    symbol: 'BTC',
    name: 'Bitcoin',
    assetClass: 'CRYPTO',
    quantity: 0.85,
    avgCostBasis: 42000,
    currentPrice: 67450,
    currentValue: 57332.50,
    dailyChangePercent: 2.31,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockCryptoAccount,
  },
  {
    id: 'h7',
    accountId: 'a2',
    symbol: 'ETH',
    name: 'Ethereum',
    assetClass: 'CRYPTO',
    quantity: 8.5,
    avgCostBasis: 2100,
    currentPrice: 3520,
    currentValue: 29920,
    dailyChangePercent: 1.85,
    currency: 'USD',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockCryptoAccount,
  },
  {
    id: 'h8',
    accountId: 'a3',
    symbol: 'ILS_CASH',
    name: 'Israeli Shekel Cash',
    assetClass: 'CASH',
    quantity: 87500,
    avgCostBasis: 1.0,
    currentPrice: 1.0,
    currentValue: 87500,
    dailyChangePercent: 0,
    currency: 'ILS',
    metadata: {},
    updatedAt: new Date().toISOString(),
    account: mockBankAccount,
  },
]

// ---------------------------------------------------------------------------
// Net Worth Summary
// ---------------------------------------------------------------------------

// ILS→USD at ~0.27 (update ILS_USD_RATE in .env to override)
const ILS_USD = parseFloat(process.env.ILS_USD_RATE ?? '0.27')
const bankUSD = 87500 * ILS_USD

export const MOCK_NET_WORTH_SUMMARY: NetWorthSummary = {
  total: bankUSD + 87382 + 198840,
  breakdown: {
    cash: bankUSD,
    crypto: 87382,
    capitalMarket: 198840,
    pension: 0,
  },
  dailyChange: 2341.50,
  dailyChangePercent: 0.76,
}

// ---------------------------------------------------------------------------
// Transactions
// ---------------------------------------------------------------------------

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString()
}

export const MOCK_TRANSACTIONS: TransactionWithRelations[] = [
  {
    id: 't1',
    accountId: 'a1',
    holdingId: 'h1',
    type: 'BUY',
    symbol: 'AAPL',
    quantity: 50,
    price: 155.0,
    amount: -7750,
    currency: 'USD',
    description: 'Initial AAPL purchase',
    date: daysAgo(180),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(180),
    account: mockBrokerageAccount,
  },
  {
    id: 't2',
    accountId: 'a1',
    holdingId: 'h2',
    type: 'BUY',
    symbol: 'GOOGL',
    quantity: 30,
    price: 140.0,
    amount: -4200,
    currency: 'USD',
    description: 'Initial GOOGL purchase',
    date: daysAgo(175),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(175),
    account: mockBrokerageAccount,
  },
  {
    id: 't3',
    accountId: 'a1',
    holdingId: 'h3',
    type: 'BUY',
    symbol: 'VOO',
    quantity: 40,
    price: 427.5,
    amount: -17100,
    currency: 'USD',
    description: 'VOO accumulation (2 tranches)',
    date: daysAgo(150),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(149),
    metadata: {},
    createdAt: daysAgo(149),
    account: mockBrokerageAccount,
  },
  {
    id: 't4',
    accountId: 'a1',
    holdingId: 'h4',
    type: 'BUY',
    symbol: 'QQQ',
    quantity: 25,
    price: 380.0,
    amount: -9500,
    currency: 'USD',
    description: 'QQQ purchase',
    date: daysAgo(140),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(139),
    metadata: {},
    createdAt: daysAgo(139),
    account: mockBrokerageAccount,
  },
  {
    id: 't5',
    accountId: 'a1',
    holdingId: 'h5',
    type: 'BUY',
    symbol: 'VTI',
    quantity: 60,
    price: 215.0,
    amount: -12900,
    currency: 'USD',
    description: 'VTI purchase',
    date: daysAgo(130),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(129),
    metadata: {},
    createdAt: daysAgo(129),
    account: mockBrokerageAccount,
  },
  {
    id: 't6',
    accountId: 'a2',
    holdingId: 'h6',
    type: 'BUY',
    symbol: 'BTC',
    quantity: 0.5,
    price: 38000,
    amount: -19000,
    currency: 'USD',
    description: 'BTC accumulation – tranche 1',
    date: daysAgo(160),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(160),
    account: mockCryptoAccount,
  },
  {
    id: 't7',
    accountId: 'a2',
    holdingId: 'h6',
    type: 'BUY',
    symbol: 'BTC',
    quantity: 0.35,
    price: 46000,
    amount: -16100,
    currency: 'USD',
    description: 'BTC accumulation – tranche 2',
    date: daysAgo(90),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(90),
    account: mockCryptoAccount,
  },
  {
    id: 't8',
    accountId: 'a2',
    holdingId: 'h7',
    type: 'BUY',
    symbol: 'ETH',
    quantity: 8.5,
    price: 2100,
    amount: -17850,
    currency: 'USD',
    description: 'ETH purchase',
    date: daysAgo(120),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(120),
    account: mockCryptoAccount,
  },
  {
    id: 't9',
    accountId: 'a3',
    holdingId: null,
    type: 'DEPOSIT',
    symbol: null,
    quantity: null,
    price: null,
    amount: 15000,
    currency: 'ILS',
    description: 'Monthly salary – March',
    date: daysAgo(30),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(30),
    account: mockBankAccount,
  },
  {
    id: 't10',
    accountId: 'a3',
    holdingId: null,
    type: 'DEPOSIT',
    symbol: null,
    quantity: null,
    price: null,
    amount: 15000,
    currency: 'ILS',
    description: 'Monthly salary – February',
    date: daysAgo(60),
    source: 'MANUAL',
    importedAt: null,
    metadata: {},
    createdAt: daysAgo(60),
    account: mockBankAccount,
  },
  {
    id: 't11',
    accountId: 'a1',
    holdingId: 'h1',
    type: 'DIVIDEND',
    symbol: 'AAPL',
    quantity: null,
    price: null,
    amount: 46.0,
    currency: 'USD',
    description: 'AAPL quarterly dividend',
    date: daysAgo(45),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(44),
    metadata: {},
    createdAt: daysAgo(44),
    account: mockBrokerageAccount,
  },
  {
    id: 't12',
    accountId: 'a1',
    holdingId: 'h3',
    type: 'DIVIDEND',
    symbol: 'VOO',
    quantity: null,
    price: null,
    amount: 156.0,
    currency: 'USD',
    description: 'VOO quarterly dividend',
    date: daysAgo(50),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(49),
    metadata: {},
    createdAt: daysAgo(49),
    account: mockBrokerageAccount,
  },
  {
    id: 't13',
    accountId: 'a1',
    holdingId: null,
    type: 'FEE',
    symbol: null,
    quantity: null,
    price: null,
    amount: -12.50,
    currency: 'USD',
    description: 'Brokerage monthly fee',
    date: daysAgo(15),
    source: 'CSV_IMPORT',
    importedAt: daysAgo(14),
    metadata: {},
    createdAt: daysAgo(14),
    account: mockBrokerageAccount,
  },
]
