/**
 * GET /api/cron/monthly-reminder
 *
 * Vercel Cron job — fires on the 3rd of every month at 08:00 AM (UTC).
 * Schedule definition lives in vercel.json: "0 8 3 * *"
 *
 * Security
 * ────────
 * Vercel automatically injects  Authorization: Bearer <CRON_SECRET>
 * on every cron invocation. Manually triggered calls must include the
 * same header. If CRON_SECRET is absent the endpoint is unprotected —
 * acceptable for local dev, never for production.
 *
 * Manual trigger (curl):
 *   curl -H "Authorization: Bearer $CRON_SECRET" \
 *        https://yourapp.vercel.app/api/cron/monthly-reminder
 *
 * Message structure (two parts)
 * ──────────────────────────────
 * Part A — Manual update checklist:
 *   Reminds the user which four data sources need to be refreshed by
 *   hand each month (bank CSV, brokerage CSV, pension app, Bitcoin wallet).
 *
 * Part B — AI insights:
 *   Generated by generatePortfolioInsights() in /lib/ai-engine.ts.
 *   Structured Hebrew analysis with Buy/Sell/Hold recommendations and
 *   a single monthly action item.
 *
 * Broadcast: WhatsApp (Twilio) and Email (Resend) are attempted in
 * parallel. A failure in one channel never blocks the other.
 */

import { NextResponse } from 'next/server'
import type { NextRequest } from 'next/server'
import type { PortfolioSnapshot } from '@/lib/monthly-reminder'
import { insightsToText } from '@/lib/ai-engine'
import type { InsightsResult } from '@/lib/ai-engine'

// ─────────────────────────────────────────────────────────────────────────────
// Message builder
// ─────────────────────────────────────────────────────────────────────────────

function ils(n: number): string {
  return `₪${Math.round(n).toLocaleString('he-IL')}`
}

const HEBREW_MONTHS = [
  'ינואר', 'פברואר', 'מרץ', 'אפריל', 'מאי', 'יוני',
  'יולי', 'אוגוסט', 'ספטמבר', 'אוקטובר', 'נובמבר', 'דצמבר',
]

function buildMonthlyMessage(
  snap: PortfolioSnapshot,
  insights: InsightsResult
): string {
  const month = HEBREW_MONTHS[new Date().getMonth()]

  const btcLine =
    snap.btcQty !== null
      ? `${snap.btcQty.toFixed(4)} BTC (≈ ${ils(snap.btcIls)})`
      : ils(snap.btcIls)

  // ── Part A: current balances + manual update checklist ──────────────────
  const partA = [
    `📊 עדכון חודשי — ${month}`,
    ``,
    `💰 ערכים במערכת כרגע:`,
    `• עו"ש (בנק דיסקונט): ${ils(snap.bankIls)}`,
    `• אקסלנס טרייד: ${ils(snap.brokerageIls)}`,
    `• פנסיה: ${ils(snap.pensionIls)}`,
    `• ביטקוין: ${btcLine}`,
    `• סה"כ: ${ils(snap.totalIls)}`,
    ``,
    `📋 יש לעדכן ידנית החודש:`,
    `☐ עו"ש — ייצא דף חשבון מבנק דיסקונט (CSV)`,
    `☐ אקסלנס טרייד — ייצא נתוני עסקאות (CSV)`,
    `☐ פנסיה — עדכן יתרה מאפליקציית קופת הגמל`,
    `☐ ביטקוין — בדוק יתרה בארנק Trezor`,
  ].join('\n')

  // ── Part B: AI insights ──────────────────────────────────────────────────
  let partB: string
  if (!insights.available) {
    partB = [`🤖 ניתוח AI:`, insights.message].join('\n')
  } else {
    partB = [`🤖 ניתוח AI לחודש ${month}:`, insightsToText(insights)].join('\n')
  }

  // ── Reply instructions ───────────────────────────────────────────────────
  const replyInstructions = [
    `📝 להשב עם הסכומים המעודכנים (המערכת תעדכן אוטומטית):`,
    `עו"ש: 52000`,
    `אקסלנס: 135000`,
    `פנסיה: 215000`,
    `ביטקוין: 0.45`,
  ].join('\n')

  return [partA, '', partB, '', replyInstructions].join('\n')
}

// ─────────────────────────────────────────────────────────────────────────────
// Handler
// ─────────────────────────────────────────────────────────────────────────────

export async function GET(request: NextRequest) {
  // ── Auth ──────────────────────────────────────────────────────────────────
  const cronSecret = process.env.CRON_SECRET
  if (cronSecret) {
    const authHeader = request.headers.get('authorization')
    if (authHeader !== `Bearer ${cronSecret}`) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }
  }

  try {
    // ── Step 1: Fetch portfolio snapshot ────────────────────────────────────
    const { fetchPortfolioSnapshot } = await import('@/lib/monthly-reminder')
    const { sendWhatsApp, sendEmail } = await import('@/lib/notifications')
    const snap = await fetchPortfolioSnapshot()

    // ── Step 2: Build EngineInput and generate Hebrew insights ──────────────
    const { generatePortfolioInsights } = await import('@/lib/ai-engine')
    const { getInvestmentThesis } = await import('@/lib/user-settings')

    const ilsToUsd = 1 / snap.ilsPerUsd  // snap.ilsPerUsd is "ILS per USD" e.g. 3.7 → ilsToUsd ≈ 0.27
    const toUsd = (ils: number) => ils * ilsToUsd

    const userThesis = await getInvestmentThesis()

    const insights = await generatePortfolioInsights({
      breakdown: {
        cash:          toUsd(snap.bankIls),
        capitalMarket: toUsd(snap.brokerageIls),
        pension:       toUsd(snap.pensionIls),
        crypto:        toUsd(snap.btcIls),
      },
      totalUsd:  toUsd(snap.totalIls),
      ilsPerUsd: snap.ilsPerUsd,
      // No holdingsSummary — cron uses bucket-level data only, not per-holding detail
      userThesis: userThesis ?? undefined,
    })

    // ── Step 3: Compose the two-part message ─────────────────────────────────
    const message = buildMonthlyMessage(snap, insights)

    // ── Step 4: Broadcast (channels are independent — one failure ≠ abort) ──
    const results: Record<string, string> = {}

    const [waResult, emailResult] = await Promise.allSettled([
      process.env.TWILIO_ACCOUNT_SID && process.env.REMINDER_WHATSAPP_TO
        ? sendWhatsApp(message)
        : Promise.reject(new Error('TWILIO_ACCOUNT_SID or REMINDER_WHATSAPP_TO not set')),
      process.env.RESEND_API_KEY && process.env.REMINDER_EMAIL_TO
        ? sendEmail(message)
        : Promise.reject(new Error('RESEND_API_KEY or REMINDER_EMAIL_TO not set')),
    ])

    results.whatsapp =
      waResult.status === 'fulfilled'
        ? 'sent'
        : `skipped/error: ${waResult.reason instanceof Error ? waResult.reason.message : String(waResult.reason)}`

    results.email =
      emailResult.status === 'fulfilled'
        ? 'sent'
        : `skipped/error: ${emailResult.reason instanceof Error ? emailResult.reason.message : String(emailResult.reason)}`

    return NextResponse.json({
      success: true,
      sentAt: new Date().toISOString(),
      aiInsightsAvailable: insights.available,
      results,
    })
  } catch (error) {
    console.error('[GET /api/cron/monthly-reminder]', error)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
